language: python
python:
    - "2.7"
before_install:
    - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
    - tar -xzf google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
    - ./google-cloud-sdk/install.sh --quiet
    - ./google-cloud-sdk/bin/gcloud components install app-engine-python --quiet
    - pip install -r requirements.txt
    - pip install -t lib -r requirements.txt
    - pip install -r requirements_tests.txt
    - pip install coveralls==1.3.0
    - pip install pylint==1.9.2
    - pip install click==6.7
    - PYTHONPATH=$PYTHONPATH:./lib:./google-cloud-sdk/bin

jobs:
  include:
    - stage: unit-tests
      script: coverage run --source=src test_runner.py --test-path tests/ --test-pattern 'test*.py' -v ./google-cloud-sdk
    - stage: isolation-tests
      script: python isolation_test.py --v --test_runner "test_runner.py" --test_path "tests" --google_cloud_sdk ./google-cloud-sdk

after_success:
  coveralls
