runtime: python27
api_version: 1
threadsafe: true

instance_class: B4
basic_scaling:
  max_instances: 25
  idle_timeout: 10m

builtins:
# Deferred is required to use google.appengine.ext.deferred.
- deferred: on

libraries:
- name: ssl
  version: 2.7.11

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  secure: always
  login: admin
- url: /restore/table/.*
  script: src.restore.table_restore_handler.app
  secure: always
  login: admin
- url: /restore/project/.*
  script: src.restore.dataset.dataset_restore_handler.app
  secure: always
  login: admin
- url: /schedule/restore/project/.*
  script: src.restore.dataset.dataset_restore_handler.app
  secure: always
- url: /restore/list
  script: src.restore.list.backup_list_restore_handler.app
  secure: always
  login: admin
- url: /schedule/restore/list
  script: src.restore.list.backup_list_restore_handler.app
  secure: always
- url: /callback/restore-finished.*
  script: src.restore.after_restore_action_handler.app
  secure: always
  login: admin
- url: /restore/jobs/.*
  script: src.restore.status.restoration_job_status_handler.app
  secure: always
  login: admin
- url: /schedule/restore/jobs/.*
  script: src.restore.status.restoration_job_status_handler.app
  secure: always
- url: /restore/schedule/table/.*
  script: src.restore.table_restore_handler.app
  secure: always
- url: /restore/test
  script: src.restore.test.restore_test_handler.app
  secure: always
  login: admin
- url: /cron/retention
  script: src.retention.retention-routing.app
  secure: always
  login: admin
- url: /retention/schedule
  script: src.retention.retention-routing.app
  secure: always
- url: /tasks/retention/table
  script: src.retention.retention-routing.app
  secure: always
  login: admin
- url: /tasks/backups/table.*
  script: src.backup.table_backup_handler.app
  secure: always
  login: admin
- url: /tasks/backups/dataset
  script: src.backup.dataset_backup_handler.app
  secure: always
  login: admin
- url: /callback/backup-created.*
  script: src.backup.after_backup_action_handler.app
  secure: always
  login: admin
- url: /tasks/copy_job_async/copy_job
  script: src.backup.copy_job_async.copy_job.copy_job_service_handler.app
  secure: always
  login: admin
- url: /tasks/copy_job_async/result_check
  script: src.backup.copy_job_async.result_check.result_check_handler.app
  secure: always
  login: admin
- url: /cron/backup
  script: src.backup.organization_backup_handler.app
  secure: always
  login: admin
- url: /backups/schedule
  script: src.backup.organization_backup_handler.app
  secure: always
- url: /_ah/start
  script: src.main.app
  secure: always
  login: admin
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  application_readable: true
- url: /.*
  script: src.main.app
  secure: always
  login: admin