runtime: python27
api_version: 1
threadsafe: true

instance_class: F4

builtins:
# Deferred is required to use google.appengine.ext.deferred.
- deferred: on

libraries:
- name: ssl
  version: 2.7.11

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- google_appengine.*
- gitlab-bbq
- docs
- tests
- src/slo

handlers:
- url: /cron/retention
  script: src.retention.retention-routing.app
  secure: always
- url: /tasks/retention/table
  script: src.retention.retention-routing.app
  secure: always
  login: admin
- url: /cron/backup
  script: src.backup.scheduler.organization.organization_backup_scheduler_handler.app
  secure: always
- url: /tasks/schedulebackup/organization.*
  script: src.backup.scheduler.organization.organization_backup_scheduler_handler.app
  secure: always
  login: admin
- url: /tasks/schedulebackup/project
  script: src.backup.scheduler.project.project_backup_scheduler_handler.app
  secure: always
  login: admin
- url: /tasks/schedulebackup/dataset
  script: src.backup.scheduler.dataset.dataset_backup_scheduler_handler.app
  secure: always
  login: admin
- url: /tasks/schedulebackup/partitionedtable
  script: src.backup.scheduler.partitioned_table.partitioned_table_backup_scheduler_handler.app
  secure: always
  login: admin
- url: /tasks/backups/table.*
  script: src.backup.table_backup_handler.app
  secure: always
  login: admin
- url: /tasks/backups/on_demand/table.*
  script: src.backup.on_demand.on_demand_table_backup_handler.app
  secure: always
- url: /callback/backup-created.*
  script: src.backup.after_backup_action_handler.app
  secure: always
  login: admin
- url: /tasks/copy_job_async/copy_job
  script: src.commons.big_query.copy_job_async.copy_job.copy_job_service_handler.app
  secure: always
  login: admin
- url: /tasks/copy_job_async/result_check
  script: src.commons.big_query.copy_job_async.result_check.result_check_handler.app
  secure: always
  login: admin
- url: /_ah/start
  script: src.restore.restore_ui_handler.app
  secure: always
  login: admin
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  application_readable: true
- url: /.*
  script: src.restore.restore_ui_handler.app
  secure: always
  login: required
