runtime: python27
api_version: 1
threadsafe: true

instance_class: B4
basic_scaling:
  max_instances: 25
  idle_timeout: 10m

builtins:
# Deferred is required to use google.appengine.ext.deferred.
- deferred: on

libraries:
- name: ssl
  version: 2.7.11

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- google_appengine.*
- gitlab-bbq
- docs
- tests
- src/slo

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  secure: always
  login: admin
- url: /restore/project/.*/dataset/.*/table/.*
  script: src.restore.table.table_restore_handler.app
  secure: always
- url: /restore/project/.*/dataset/.*
  script: src.restore.dataset.dataset_restore_handler.app
  secure: always
- url: /restore/list
  script: src.restore.list.backup_list_restore_handler.app
  secure: always
- url: /callback/restore-finished.*
  script: src.restore.after_restore_action_handler.app
  secure: always
  login: admin
- url: /restore/jobs/.*
  script: src.restore.status.restoration_job_status_handler.app
  secure: always
- url: /cron/retention
  script: src.retention.retention-routing.app
  secure: always
- url: /tasks/retention/table
  script: src.retention.retention-routing.app
  secure: always
  login: admin
- url: /tasks/backups/table.*
  script: src.backup.table_backup_handler.app
  secure: always
  login: admin
- url: /tasks/backups/on_demand/table.*
  script: src.backup.on_demand.on_demand_table_backup_handler.app
  secure: always
- url: /tasks/backups/dataset
  script: src.backup.dataset_backup_handler.app
  secure: always
  login: admin
- url: /callback/backup-created.*
  script: src.backup.after_backup_action_handler.app
  secure: always
  login: admin
- url: /tasks/copy_job_async/copy_job
  script: src.commons.big_query.copy_job_async.copy_job.copy_job_service_handler.app
  secure: always
  login: admin
- url: /tasks/copy_job_async/result_check
  script: src.commons.big_query.copy_job_async.result_check.result_check_handler.app
  secure: always
  login: admin
- url: /cron/backup
  script: src.backup.organization_backup_handler.app
  secure: always
- url: /cron/export-datastore-to-big-query
  script: src.datastore_export.export_datastore_to_big_query_handler.app
  secure: always
  login: admin
- url: /_ah/start
  script: src.restore.restore_ui_handler.app
  secure: always
  login: admin
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  application_readable: true
- url: /.*
  script: src.restore.restore_ui_handler.app
  secure: always
  login: required
