copy_jobs:
  copy_job_result_check_countdown_in_sec: 5

backup_settings:
  backup_worker_max_countdown_in_sec: 0
  custom_project_list: [] #list of projects to backup. If empty, BBQ will backup everything it has read (BigQuery Data Viewer) access to. If list is provided you still need to grant BigQuery Data Viewer role for BBQ service account for each mentioned projects.

  projects_to_skip: ['<your-project-id-for-BBQ-project>'] #list of projects to skip (it's recommended to skip BBQ project itself). It is useful when you grant BigQuery Data Viewer for BBQ service account for the whole organization or folder and want to exclude some of the projects.


project_settings:
  backup_project_id: '<your-project-id-for-BBQ-project>' #project id where backups will be stored (it ussualy is the same project on which BBQ runs)
  restoration_project_id: '<your-project-id-for-restoration-project>'  #project into which data will be restored during restoration process
  debug_mode: False
