copy_jobs:
  copy_job_result_check_countdown_in_sec: 5

backup_settings:
  backup_worker_max_countdown_in_sec: 0

  # custom_project_list - list of projects to backup. If empty, BBQ will backup everything
  # it has read (BigQuery Data Viewer) access to. If list is provided you still need to grant
  # BigQuery Data Viewer role for BBQ service account for each mentioned projects.
  custom_project_list: []

  # projects_to_skip - list of projects to skip (it's recommended to skip BBQ project itself).
  # It is useful when you grant BigQuery Data Viewer for BBQ service account for
  # the whole organization or folder and want to exclude some of the projects.
  projects_to_skip: ['BBQ-project-id']


project_settings:

  # backup_project_id - project id where backups will be stored
  # (it usually is the same project on which BBQ runs)
  backup_project_id: 'BBQ-project-id'
  debug_mode: False

  # default_restoration_project_id - project into which data will be restored by default during restoration process
  # default_restoration_project_id: 'default-restoration-storage-project-id'

tests:
  restoration_daily_test_results_gcs_bucket: 'a-gcs-bucket'
  random_table_view: 'project:dataset.table'
