copy_jobs:
  copy_job_result_check_countdown_in_sec: 5

backup_settings:
  backup_worker_max_countdown_in_sec: 0
  custom_project_list: []
  projects_to_skip: ['<your-project-id>']

project_settings:
  backup_project_id: '<your-project-id>'
  restoration_project_id: '<your-project-id>'
  authorized_requestor_service_accounts: ['sa-eligible-to-read-data@your-project-id.iam.gserviceaccount.com']
  debug_mode: True

tests:
  restoration_daily_test_results_gcs_bucket: 'a-gcs-bucket'
  random_table_view: 'project:dataset.table'
