copy_jobs:
  copy_job_result_check_countdown_in_sec: 5

backup_settings:
  # custom_project_list - list of projects to backup. If empty, BBQ will backup everything
  # it has read (BigQuery Data Viewer) access to. If list is provided you still need to grant
  # BigQuery Data Viewer role for BBQ service account for each mentioned projects.
  custom_project_list: []

  # projects_to_skip - list of projects to skip (it's recommended to skip BBQ project itself).
  # It is useful when you grant BigQuery Data Viewer for BBQ service account for
  # the whole organization or folder and want to exclude some of the projects.
  projects_to_skip: ['BBQ-project-id']


project_settings:

  # backup_project_id - project id where backups will be stored
  # (it usually is the same project on which BBQ runs)
  backup_project_id: 'BBQ-project-id'
  debug_mode: False

  # metadata_storage_project_id -
  # The main purpose of this project is to separate BBQ backups
  #   that should be immutable and invisible for developers without any particular reason
  # from metadata such as datastore exports, SLI views etc.
  #   that are used and constantly modified by developers.
  metadata_storage_project_id: 'BBQ-metadata-project-id'

  # default_restoration_project_id - project into which data will be restored by default during restoration process
  # default_restoration_project_id: 'default-restoration-storage-project-id'

retention_settings:

  # young_old_generation_threshold_in_months - for all backups older than this number of months,
  # retention process will delete all backups except the most recent one.
  # This doesn't affect backups younger than this threshold
  young_old_generation_threshold_in_months: 7

  # grace_period_after_source_table_deletion_in_months - number of months since deletion of source table after retention will remove last backup for given table
  grace_period_after_source_table_deletion_in_months: 7


