total_storage_limit: 10G
queue:
- name: default
  rate: 100/s
  max_concurrent_requests: 100
  bucket_size: 20
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h
- name: table-retention-scheduler
  rate: 10/s
  max_concurrent_requests: 20
  bucket_size: 20
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h
- name: table-retention
  rate: 100/s
  max_concurrent_requests: 100
  bucket_size: 100
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h
- name: backup-scheduler
  rate: 10/s
  max_concurrent_requests: 20
  bucket_size: 20
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h
- name: backup-worker
  rate: 100/s
  max_concurrent_requests: 100
  bucket_size: 20
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h

- name: backups-post-copy-action
  rate: 5/s
  bucket_size: 1
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h

- name: backups-copy-job
  rate: 5/s
  bucket_size: 1
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h

- name: backups-result-check
  rate: 5/s
  bucket_size: 1
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h

- name: restore-copy-job
  rate: 5/s
  bucket_size: 1
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h

- name: restore-result-check
  rate: 20/s
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h

- name: restore-post-copy-action
  rate: 5/s
  bucket_size: 1
  retry_parameters:
    task_retry_limit: 5
    task_age_limit: 1h