copy_jobs:
  copy_job_result_check_countdown_in_sec: 5

backup_settings:
  backup_worker_max_countdown_in_sec: 0
  custom_project_list: ['a-project-to-backup']
  projects_to_skip: ['a-project-to-skip']

project_settings:
  backup_project_id: 'your-project-name'
  restoration_project_id: 'your-project-name'
  authorized_requestor_service_accounts: ['sa-eligible-to-read-data@your-project-name.iam.gserviceaccount.com']