copy_jobs:
  copy_job_result_check_countdown_in_sec: 5

backup_settings:
  backup_worker_max_countdown_in_sec: 0
  custom_project_list: []
  projects_to_skip: ['<your-project-id>']

project_settings:
  backup_project_id: '<your-project-id>'
  restoration_project_id: '<your-project-id>'
